name: CI

on:
  pull_request:
  push:
    branches:
    - "main"

jobs:
  lint:
    name: Go lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3.0.0
      - uses: golangci/golangci-lint-action@5c56cd6c9dc07901af25baab6f2b0d9f3b7c3018 # renovate: tag=v2.5.2
        with:
          version: latest

  test:
    name: Go test & coverage
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3.0.0
        with:
          fetch-depth: 2 # See https://community.codecov.com/t/issue-detecting-commit-sha-please-run-actions-checkout-with-fetch-depth-1-or-set-to-0/2571
      - uses: actions/setup-go@331ce1d993939866bb63c32c6cbbfd48fa76fc57 # renovate: tag=v2.1.4
        with:
          go-version: 1.17.x
      - run: go test -race -coverprofile=coverage.txt -covermode=atomic -v ./...
      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash)
