name: goreleaser

on:
  push:
    tags:
      - '*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # renovate: tag=v3.0.2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@fcdc43634adb5f7ae75a9d7a9b9361790f7293e2 # renovate: tag=v3.1.0
        with:
          go-version: 1.18
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@b953231f81b8dfd023c58e0854a721e35037f28b # renovate: tag=v2.9.1
        with:
          distribution: goreleaser
          # renovate: datasource=github-tags depName=goreleaser/goreleaser versioning=semver
          version: v1.8.3
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
